
# ~BrieFlow analysis configuration file~

# All paths are resolved relative to the directory the workflow is run from.

# Parameters:
all:
  root_fp: "/home/tubhi/tubhi-phenotyping-temp/brieflow_preprocessing_output/dual_sgrna"
preprocess:
  sbs_samples_fp: config/sbs_samples_dualsgrna.tsv
  sbs_combo_fp: config/sbs_combo.tsv
  phenotype_samples_fp: config/phenotype_samples.tsv
  phenotype_combo_fp: config/phenotype_combo.tsv
  sbs_channel_order: null
  phenotype_channel_order: null
  phenotype_round_order: null
  sbs_channel_order_flip: null
  phenotype_channel_order_flip: null
  sample_fraction: 1.0
